name: Create GitHub Release

on:
  push:
    branches:
      - main
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release for Version Bump
        uses: justincy/github-action-npm-release@2.0.2
        id: create_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
